import { z } from 'zod'
import { executeNode } from '../runtime/executors'

const scheduleTriggerConfigSchema = z.object({
  triggerMode: z.string().optional(),
  scheduleMode: z.enum(['cron', 'every', 'once']),
  cronExpression: z.string().optional(),
  every: z.string().optional(),
  everyMinutes: z.number().optional(),
  runAt: z.string().optional(),
  timezone: z.string().min(1),
  enabled: z.boolean().optional(),
  triggerLabel: z.string().optional(),
  scheduleSummary: z.string().optional(),
  cronJobId: z.string().nullable().optional(),
  scheduleBindingId: z.string().nullable().optional(),
}).superRefine((config, ctx) => {
  if (config.scheduleMode === 'cron' && !config.cronExpression) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'cronExpression is required for cron schedule mode' })
  }
  if (config.scheduleMode === 'every' && !config.every && !config.everyMinutes) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'every or everyMinutes is required for every schedule mode' })
  }
  if (config.scheduleMode === 'once' && !config.runAt) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'runAt is required for once schedule mode' })
  }
})

const promptConfigSchema = z.object({
  runtimeTarget: z.string().min(1),
  inputMapping: z.record(z.string(), z.any()).optional(),
  outputMode: z.string().optional(),
  expectedSchema: z.record(z.string(), z.any()).optional(),
  audience: z.string().optional(),
  theme: z.string().optional(),
})

const googleDriveSaveFileConfigSchema = z.object({
  targetAccount: z.string().optional(),
  accountId: z.string().optional(),
  destination: z.string().min(1),
  fileNameTemplate: z.string().min(1),
  contentMapping: z.string().optional(),
  contentType: z.string().min(1).optional(),
})

const downloadFileConfigSchema = z.object({
  fileNameTemplate: z.string().min(1),
  contentMapping: z.string().optional(),
  contentType: z.string().min(1).optional(),
})

const sendMessageConfigSchema = z.object({
  destinationType: z.string().optional(),
  destination: z.string().min(1),
})

const returnResultConfigSchema = z.object({
  visibleInApp: z.boolean().optional(),
  displayMode: z.string().optional(),
})

const simpleOptionalTextConfigSchema = z.object({}).passthrough()

const approvalConfigSchema = z.object({
  allowedDecisions: z.array(z.string()).optional(),
  editableFields: z.array(z.string()).optional(),
})

export const nodeDefinitions = {
  'trigger.schedule': {
    toolId: 'trigger.schedule',
    title: 'Schedule Trigger',
    description: 'Start a workflow on a real schedule.',
    nodeType: 'trigger',
    toolKind: 'system',
    defaultLabel: 'Schedule Trigger',
    defaultConfig: {
      triggerMode: 'schedule',
      scheduleMode: 'cron',
      cronExpression: '0 7 * * 1-5',
      timezone: 'America/Los_Angeles',
      enabled: true,
      triggerLabel: 'Scheduled workflow',
      scheduleSummary: 'Every weekday at 7:00 AM',
      cronJobId: null,
      scheduleBindingId: null,
    },
    configSchema: scheduleTriggerConfigSchema,
    editorFields: [
      { key: 'scheduleMode', label: 'Mode', type: 'select', required: true },
      { key: 'cronExpression', label: 'Cron', type: 'text' },
      { key: 'every', label: 'Every', type: 'text' },
      { key: 'runAt', label: 'Run At', type: 'text' },
      { key: 'timezone', label: 'Timezone', type: 'text', required: true },
      { key: 'enabled', label: 'Enabled', type: 'boolean' },
      { key: 'triggerLabel', label: 'Trigger Label', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Reusable schedule primitive' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'ai.prompt': {
    toolId: 'ai.prompt',
    title: 'Prompt',
    description: 'Run a prompt and return text output.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Prompt',
    defaultConfig: { runtimeTarget: 'daedalus' },
    configSchema: promptConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text', required: true },
      { key: 'outputMode', label: 'Output Mode', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Core reusable AI primitive' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'ai.prompt.edit': {
    toolId: 'ai.prompt.edit',
    title: 'Prompt',
    description: 'Run an editing prompt and return text output.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Prompt',
    defaultConfig: { runtimeTarget: 'daedalus' },
    configSchema: promptConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text', required: true },
      { key: 'outputMode', label: 'Output Mode', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Core reusable AI primitive' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'ai.structured_prompt': {
    toolId: 'ai.structured_prompt',
    title: 'Structured Prompt',
    description: 'Run a prompt and return structured output.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Structured Prompt',
    defaultConfig: { runtimeTarget: 'daedalus' },
    configSchema: promptConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text', required: true },
      { key: 'expectedSchema', label: 'Expected Schema', type: 'schema' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Core reusable AI primitive' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'integrations.google_drive.save_file': {
    toolId: 'integrations.google_drive.save_file',
    title: 'Google Drive Save File',
    description: 'Save generated content to Google Drive.',
    nodeType: 'output',
    toolKind: 'integration',
    defaultLabel: 'Google Drive Save File',
    defaultConfig: {
      destination: 'Workflow Studio',
      fileNameTemplate: '{{title}}.txt',
      contentType: 'text/plain',
    },
    configSchema: googleDriveSaveFileConfigSchema,
    editorFields: [
      { key: 'destination', label: 'Destination', type: 'text', required: true },
      { key: 'fileNameTemplate', label: 'File Name Template', type: 'text', required: true },
      { key: 'accountId', label: 'Account', type: 'select' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Useful reusable integration output' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'outputs.download_file': {
    toolId: 'outputs.download_file',
    title: 'Download File',
    description: 'Prepare a downloadable artifact.',
    nodeType: 'output',
    toolKind: 'ui',
    defaultLabel: 'Download File',
    defaultConfig: {
      fileNameTemplate: '{{title}}.txt',
      contentType: 'text/plain',
    },
    configSchema: downloadFileConfigSchema,
    editorFields: [
      { key: 'fileNameTemplate', label: 'File Name Template', type: 'text', required: true },
      { key: 'contentType', label: 'Content Type', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Reusable terminal artifact output' },
    maturity: 'real',
    executor: executeNode,
  },
  'outputs.send_message': {
    toolId: 'outputs.send_message',
    title: 'Send Message',
    description: 'Deliver content to a configured destination.',
    nodeType: 'output',
    toolKind: 'delivery',
    defaultLabel: 'Send Message',
    defaultConfig: {
      destinationType: 'telegram-dm',
      destination: 'Unconfigured destination',
    },
    configSchema: sendMessageConfigSchema,
    editorFields: [
      { key: 'destinationType', label: 'Destination Type', type: 'text' },
      { key: 'destination', label: 'Destination', type: 'text', required: true },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Reusable delivery node candidate' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'outputs.return_result': {
    toolId: 'outputs.return_result',
    title: 'Return Result',
    description: 'Return a final in-app result.',
    nodeType: 'output',
    toolKind: 'ui',
    defaultLabel: 'Return Result',
    defaultConfig: { visibleInApp: true },
    configSchema: returnResultConfigSchema,
    editorFields: [
      { key: 'visibleInApp', label: 'Visible In App', type: 'boolean' },
      { key: 'displayMode', label: 'Display Mode', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'live', reason: 'Reusable terminal UI node' },
    maturity: 'fallback-only',
    executor: executeNode,
  },
  'logic.select_theme': {
    toolId: 'logic.select_theme',
    title: 'Select Theme',
    description: 'Select or generate a working roundup theme.',
    nodeType: 'transform',
    toolKind: 'logic',
    defaultLabel: 'Select Theme',
    defaultConfig: { selectionMode: 'guided', allowThemeGeneration: true },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'nicheId', label: 'Niche Id', type: 'text' },
      { key: 'selectionMode', label: 'Selection Mode', type: 'select', options: [{ value: 'manual', label: 'Manual' }, { value: 'guided', label: 'Guided' }, { value: 'generate', label: 'Generate' }] },
      { key: 'allowThemeGeneration', label: 'Allow Theme Generation', type: 'boolean' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'sources.product_candidates': {
    toolId: 'sources.product_candidates',
    title: 'Load Product Candidates',
    description: 'Load candidate products for the selected niche/theme.',
    nodeType: 'input',
    toolKind: 'source',
    defaultLabel: 'Load Product Candidates',
    defaultConfig: { sourceType: 'manual-import', maxCandidates: 50, productsJson: '', productLines: '', includeAffiliateFields: true },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'sourceType', label: 'Source Type', type: 'select', options: [{ value: 'manual-import', label: 'Manual Import' }, { value: 'csv', label: 'CSV' }, { value: 'feed', label: 'Feed' }, { value: 'inline-json', label: 'Inline JSON' }, { value: 'quick-paste', label: 'Quick Paste' }, { value: 'research', label: 'Research' }] },
      { key: 'maxCandidates', label: 'Max Candidates', type: 'text' },
      { key: 'sourceRef', label: 'Source Ref', type: 'text' },
      { key: 'productLines', label: 'Quick Paste Lines', type: 'schema' },
      { key: 'productsJson', label: 'Products JSON', type: 'schema' },
      { key: 'includeAffiliateFields', label: 'Include Affiliate Fields', type: 'boolean' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'data.normalize_records': {
    toolId: 'data.normalize_records',
    title: 'Normalize Records',
    description: 'Normalize structured records to predictable fields.',
    nodeType: 'transform',
    toolKind: 'data',
    defaultLabel: 'Normalize Records',
    defaultConfig: {},
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'normalizeFields', label: 'Normalize Fields', type: 'schema' },
      { key: 'mappingProfile', label: 'Mapping Profile', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'data.dedupe_records': {
    toolId: 'data.dedupe_records',
    title: 'Dedupe Records',
    description: 'Remove duplicates and cluster similar products.',
    nodeType: 'transform',
    toolKind: 'data',
    defaultLabel: 'Dedupe Records',
    defaultConfig: { dedupeStrategy: 'exact-plus-fuzzy', fuzzyThreshold: 0.9 },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'dedupeStrategy', label: 'Dedupe Strategy', type: 'select', options: [{ value: 'exact', label: 'Exact' }, { value: 'exact-plus-fuzzy', label: 'Exact + Fuzzy' }] },
      { key: 'fuzzyThreshold', label: 'Fuzzy Threshold', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'approval.review_candidates': {
    toolId: 'approval.review_candidates',
    title: 'Review Candidates',
    description: 'Present candidate products for structured human approval before scoring.',
    nodeType: 'approval',
    toolKind: 'approval',
    defaultLabel: 'Review Candidates',
    defaultConfig: { allowedDecisions: ['approved', 'rejected'], defaultDecision: 'approved', minApprovedCount: 3 },
    configSchema: approvalConfigSchema,
    editorFields: [
      { key: 'allowedDecisions', label: 'Allowed Decisions', type: 'schema' },
      { key: 'defaultDecision', label: 'Default Decision', type: 'text' },
      { key: 'editableFields', label: 'Editable Fields', type: 'schema' },
      { key: 'minApprovedCount', label: 'Minimum Approved Count', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'logic.filter_approved_candidates': {
    toolId: 'logic.filter_approved_candidates',
    title: 'Filter Approved Candidates',
    description: 'Keep only approved candidates before ranking.',
    nodeType: 'transform',
    toolKind: 'logic',
    defaultLabel: 'Filter Approved Candidates',
    defaultConfig: { fallbackMode: 'top-reviewed', minApprovedCount: 3 },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'fallbackMode', label: 'Fallback Mode', type: 'select', options: [{ value: 'none', label: 'None' }, { value: 'top-reviewed', label: 'Top Reviewed' }] },
      { key: 'minApprovedCount', label: 'Minimum Approved Count', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'logic.score_products': {
    toolId: 'logic.score_products',
    title: 'Score Products',
    description: 'Apply weighted scoring across candidate products.',
    nodeType: 'transform',
    toolKind: 'logic',
    defaultLabel: 'Score Products',
    defaultConfig: { weightsProfile: 'default', topK: 20 },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'weightsProfile', label: 'Weights Profile', type: 'text' },
      { key: 'topK', label: 'Top K', type: 'text' },
      { key: 'minimumScore', label: 'Minimum Score', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'logic.select_roundup_set': {
    toolId: 'logic.select_roundup_set',
    title: 'Select Roundup Set',
    description: 'Choose final products and alternates for the roundup.',
    nodeType: 'transform',
    toolKind: 'logic',
    defaultLabel: 'Select Roundup Set',
    defaultConfig: { targetCount: 10, alternateCount: 4, enforceThemeCoherence: true },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'targetCount', label: 'Target Count', type: 'text' },
      { key: 'alternateCount', label: 'Alternate Count', type: 'text' },
      { key: 'enforceThemeCoherence', label: 'Enforce Theme Coherence', type: 'boolean' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'ai.generate_content_pack': {
    toolId: 'ai.generate_content_pack',
    title: 'Generate Content Pack',
    description: 'Generate disclosure-aware copy package.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Generate Content Pack',
    defaultConfig: { runtimeTarget: 'daedalus', channel: 'pinterest' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'text' },
      { key: 'nicheTone', label: 'Niche Tone', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'ai.generate_creative_briefs': {
    toolId: 'ai.generate_creative_briefs',
    title: 'Generate Creative Briefs',
    description: 'Generate Pinterest-first creative directions.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Generate Creative Briefs',
    defaultConfig: { runtimeTarget: 'daedalus', assetCount: 4, channel: 'pinterest' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text' },
      { key: 'assetCount', label: 'Asset Count', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'data.assemble_content_pack': {
    toolId: 'data.assemble_content_pack',
    title: 'Assemble Content Pack',
    description: 'Package content artifacts into a review-ready object.',
    nodeType: 'transform',
    toolKind: 'data',
    defaultLabel: 'Assemble Content Pack',
    defaultConfig: { initialStatus: 'review', includeAlternates: true },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'initialStatus', label: 'Initial Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'review', label: 'Review' }, { value: 'approved', label: 'Approved' }] },
      { key: 'includeAlternates', label: 'Include Alternates', type: 'boolean' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'approval.review_content_pack': {
    toolId: 'approval.review_content_pack',
    title: 'Review Content Pack',
    description: 'Present a content pack for structured human approval.',
    nodeType: 'approval',
    toolKind: 'approval',
    defaultLabel: 'Review Content Pack',
    defaultConfig: { allowedDecisions: ['approved', 'rework', 'rejected', 'deferred'] },
    configSchema: approvalConfigSchema,
    editorFields: [
      { key: 'allowedDecisions', label: 'Allowed Decisions', type: 'schema' },
      { key: 'editableFields', label: 'Editable Fields', type: 'schema' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'logic.approval_branch': {
    toolId: 'logic.approval_branch',
    title: 'Approval Branch',
    description: 'Route approval outcomes deterministically.',
    nodeType: 'branch',
    toolKind: 'logic',
    defaultLabel: 'Approval Branch',
    defaultConfig: { approvedRoute: 'schedule', reworkRoute: 'return' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'approvedRoute', label: 'Approved Route', type: 'text' },
      { key: 'reworkRoute', label: 'Rework Route', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'outputs.create_publish_job': {
    toolId: 'outputs.create_publish_job',
    title: 'Create Publish Job',
    description: 'Create a publish/schedule artifact for Pinterest.',
    nodeType: 'output',
    toolKind: 'delivery',
    defaultLabel: 'Create Publish Job',
    defaultConfig: { channel: 'pinterest', mode: 'export-or-direct' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'channel', label: 'Channel', type: 'text' },
      { key: 'board', label: 'Board', type: 'text' },
      { key: 'mode', label: 'Mode', type: 'select', options: [{ value: 'export', label: 'Export' }, { value: 'direct', label: 'Direct' }, { value: 'export-or-direct', label: 'Export or Direct' }] },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'inputs.load_content_pack': {
    toolId: 'inputs.load_content_pack',
    title: 'Load Content Pack',
    description: 'Load a content pack by id or status.',
    nodeType: 'input',
    toolKind: 'storage',
    defaultLabel: 'Load Content Pack',
    defaultConfig: { contentPackStatus: 'review' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'contentPackId', label: 'Content Pack Id', type: 'text' },
      { key: 'contentPackStatus', label: 'Content Pack Status', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'inputs.load_published_packs': {
    toolId: 'inputs.load_published_packs',
    title: 'Load Published Content Packs',
    description: 'Load recently published content packs.',
    nodeType: 'input',
    toolKind: 'storage',
    defaultLabel: 'Load Published Content Packs',
    defaultConfig: { windowDays: 30, channel: 'pinterest' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'windowDays', label: 'Window Days', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'inputs.fetch_channel_metrics': {
    toolId: 'inputs.fetch_channel_metrics',
    title: 'Fetch Channel Metrics',
    description: 'Fetch or import recent channel metrics.',
    nodeType: 'input',
    toolKind: 'integration',
    defaultLabel: 'Fetch Channel Metrics',
    defaultConfig: { provider: 'pinterest', mode: 'import-or-direct' },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'provider', label: 'Provider', type: 'text' },
      { key: 'mode', label: 'Mode', type: 'select', options: [{ value: 'import', label: 'Import' }, { value: 'direct', label: 'Direct' }, { value: 'import-or-direct', label: 'Import or Direct' }] },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'logic.review_performance': {
    toolId: 'logic.review_performance',
    title: 'Review Performance',
    description: 'Summarize patterns across published content.',
    nodeType: 'transform',
    toolKind: 'logic',
    defaultLabel: 'Review Performance',
    defaultConfig: {},
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'groupBy', label: 'Group By', type: 'schema' },
      { key: 'primaryMetrics', label: 'Primary Metrics', type: 'schema' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
  'ai.recommend_next_themes': {
    toolId: 'ai.recommend_next_themes',
    title: 'Recommend Next Themes',
    description: 'Recommend future themes from performance learnings.',
    nodeType: 'tool',
    toolKind: 'openclaw',
    defaultLabel: 'Recommend Next Themes',
    defaultConfig: { runtimeTarget: 'daedalus', recommendationCount: 5 },
    configSchema: simpleOptionalTextConfigSchema,
    editorFields: [
      { key: 'runtimeTarget', label: 'Runtime Target', type: 'text' },
      { key: 'recommendationCount', label: 'Recommendation Count', type: 'text' },
    ],
    organizer: { ready: true, visibility: 'design-target', reason: 'Flagship affiliate workflow primitive' },
    maturity: 'scaffold',
    executor: executeNode,
  },
}
